//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestMail.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GestMail.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Licencia activa.
        /// </summary>
        internal static string ACTIVE_LICENSE {
            get {
                return ResourceManager.GetString("ACTIVE_LICENSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Activar Producto.
        /// </summary>
        internal static string ACTIVE_PRODUCT {
            get {
                return ResourceManager.GetString("ACTIVE_PRODUCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Errores de configuración.
        /// </summary>
        internal static string CONFIG_ERRORS {
            get {
                return ResourceManager.GetString("CONFIG_ERRORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminado con éxito.
        /// </summary>
        internal static string CORRECT_DELETE {
            get {
                return ResourceManager.GetString("CORRECT_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Errores reportados con éxito.
        /// </summary>
        internal static string CORRECT_ERRORS_REPORT {
            get {
                return ResourceManager.GetString("CORRECT_ERRORS_REPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardado con éxito.
        /// </summary>
        internal static string CORRECT_SAVE {
            get {
                return ResourceManager.GetString("CORRECT_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Facturas.
        /// </summary>
        internal static string EMAIL_CUSTOMER_SUBJECT {
            get {
                return ResourceManager.GetString("EMAIL_CUSTOMER_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GestMail Test mail.
        /// </summary>
        internal static string EMAIL_TEST_SUBJECT {
            get {
                return ResourceManager.GetString("EMAIL_TEST_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reportar errores.
        /// </summary>
        internal static string ERRORS_REPORT {
            get {
                return ResourceManager.GetString("ERRORS_REPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Licencia expirada.
        /// </summary>
        internal static string EXPIRED_LICESE {
            get {
                return ResourceManager.GetString("EXPIRED_LICESE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ico {
            get {
                object obj = ResourceManager.GetObject("ico", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Icon similar a (Icono).
        /// </summary>
        internal static System.Drawing.Icon ico1 {
            get {
                object obj = ResourceManager.GetObject("ico1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuración incompleta.
        /// </summary>
        internal static string INCOMPLETE_CONFIG {
            get {
                return ResourceManager.GetString("INCOMPLETE_CONFIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La clave de producto introducida no es correcta.
        /// </summary>
        internal static string LICENSE_KEY_NO_VALID {
            get {
                return ResourceManager.GetString("LICENSE_KEY_NO_VALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe cubrir todos los parametros de configuración.
        /// </summary>
        internal static string MUST_WRITE_ANY_CONFIG {
            get {
                return ResourceManager.GetString("MUST_WRITE_ANY_CONFIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No es posible eliminar, este cliente tiene facturas asociadas.
        /// </summary>
        internal static string NO_POSIBLE_DELETE_CUSTOMER {
            get {
                return ResourceManager.GetString("NO_POSIBLE_DELETE_CUSTOMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alguno de los emails no pasa las validaciones de formato.
        /// </summary>
        internal static string NO_VALID_EMAIL_FORMAT {
            get {
                return ResourceManager.GetString("NO_VALID_EMAIL_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Producto activado.
        /// </summary>
        internal static string PRODUCT_ACTIVATE {
            get {
                return ResourceManager.GetString("PRODUCT_ACTIVATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar configuración.
        /// </summary>
        internal static string SAVE_CONFIG {
            get {
                return ResourceManager.GetString("SAVE_CONFIG", resourceCulture);
            }
        }
    }
}
