//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestMail.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GestMail.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licencia activa.
        /// </summary>
        internal static string ACTIVE_LICENSE {
            get {
                return ResourceManager.GetString("ACTIVE_LICENSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activar Producto.
        /// </summary>
        internal static string ACTIVE_PRODUCT {
            get {
                return ResourceManager.GetString("ACTIVE_PRODUCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errores de configuración.
        /// </summary>
        internal static string CONFIG_ERRORS {
            get {
                return ResourceManager.GetString("CONFIG_ERRORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminado con éxito.
        /// </summary>
        internal static string CORRECT_DELETE {
            get {
                return ResourceManager.GetString("CORRECT_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errores reportados con éxito.
        /// </summary>
        internal static string CORRECT_ERRORS_REPORT {
            get {
                return ResourceManager.GetString("CORRECT_ERRORS_REPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardado con éxito.
        /// </summary>
        internal static string CORRECT_SAVE {
            get {
                return ResourceManager.GetString("CORRECT_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facturas.
        /// </summary>
        internal static string EMAIL_CUSTOMER_SUBJECT {
            get {
                return ResourceManager.GetString("EMAIL_CUSTOMER_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GestMail Test mail.
        /// </summary>
        internal static string EMAIL_TEST_SUBJECT {
            get {
                return ResourceManager.GetString("EMAIL_TEST_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reportar errores.
        /// </summary>
        internal static string ERRORS_REPORT {
            get {
                return ResourceManager.GetString("ERRORS_REPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licencia expirada.
        /// </summary>
        internal static string EXPIRED_LICESE {
            get {
                return ResourceManager.GetString("EXPIRED_LICESE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ico {
            get {
                object obj = ResourceManager.GetObject("ico", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ico1 {
            get {
                object obj = ResourceManager.GetObject("ico1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuración incompleta.
        /// </summary>
        internal static string INCOMPLETE_CONFIG {
            get {
                return ResourceManager.GetString("INCOMPLETE_CONFIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La clave de producto introducida no es correcta.
        /// </summary>
        internal static string LICENSE_KEY_NO_VALID {
            get {
                return ResourceManager.GetString("LICENSE_KEY_NO_VALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe cubrir todos los parametros de configuración.
        /// </summary>
        internal static string MUST_WRITE_ANY_CONFIG {
            get {
                return ResourceManager.GetString("MUST_WRITE_ANY_CONFIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible eliminar, este cliente tiene facturas asociadas.
        /// </summary>
        internal static string NO_POSIBLE_DELETE_CUSTOMER {
            get {
                return ResourceManager.GetString("NO_POSIBLE_DELETE_CUSTOMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alguno de los emails no pasa las validaciones de formato.
        /// </summary>
        internal static string NO_VALID_EMAIL_FORMAT {
            get {
                return ResourceManager.GetString("NO_VALID_EMAIL_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Producto activado.
        /// </summary>
        internal static string PRODUCT_ACTIVATE {
            get {
                return ResourceManager.GetString("PRODUCT_ACTIVATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar configuración.
        /// </summary>
        internal static string SAVE_CONFIG {
            get {
                return ResourceManager.GetString("SAVE_CONFIG", resourceCulture);
            }
        }
    }
}
